# This is a Docker Compose configuration
# intended for development purposes only

version: '3'

volumes:
  db: {}

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: bookstack-dev
      MYSQL_USER: enlith
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dev/docker/init.db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    networks:
      default: null
  app:
    build:
      context: .
      dockerfile: ./dev/docker/Dockerfile
    environment:
      APP_URL: http://${DOCKER_GATEWAY_HOST:-localhost}:9080
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bookstack-dev
      DB_USERNAME: enlith
      DB_PASSWORD: test
      TEST_DATABASE_URL: mysql://enlith:test@db/bookstack-test
      MAIL_DRIVER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      PGID: 0
      PUID: 0
    ports:
      - 9080:80
    volumes:
      - /share/bookstack/:/bookstack
      - ./:/app
    dns:
      - 8.8.8.8
    networks:
      default: null
    entrypoint: /app/dev/docker/entrypoint.app.sh
  node:
    image: node:alpine
    working_dir: /app
    user: node
    command: tail -F anything
    environment:
      PGID: 0
      PUID: 0
    volumes:
      - /share/bookstack/:/bookstack
      - ./:/app
    dns:
      - 8.8.8.8
    networks:
      default: null
    entrypoint: /app/dev/docker/entrypoint.node.sh
  mailhog:
    image: mailhog/mailhog
    ports:
      - 9025:8025
    dns:
      - 8.8.8.8
    networks:
      default: null

networks:
  default:
    driver: bridge
